virtual_map:
  - intersection_id: 1
    signal_group: 101
    waypoint_id: 5001
    latitude: 37.7749
    longitude: -122.4194

  - intersection_id: 2
    signal_group: 102
    waypoint_id: 5002
    latitude: 37.7750
    longitude: -122.4195